/*
 Jaffar Shorbaji
 makingPurchases.java
 Ocober 5, 2018
 This program is a program
 */

/**
 *
 * @author jasho9017
 */
import java.util.Scanner; 
public class makingPurchases extends javax.swing.JFrame {
 
    /**
     * Creates new form makingPurchases
     */
    public makingPurchases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        storeLogoLabeleth = new javax.swing.JLabel();
        storeLogoLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        subheading = new javax.swing.JLabel();
        subSubheading = new javax.swing.JLabel();
        itemLabel1 = new javax.swing.JLabel();
        amountSelectInput = new javax.swing.JTextField();
        itemLabel2 = new javax.swing.JLabel();
        amountSelectInput2 = new javax.swing.JTextField();
        subHeading2 = new javax.swing.JLabel();
        subHeading3 = new javax.swing.JLabel();
        itemLabel3 = new javax.swing.JLabel();
        amountSelectInput3 = new javax.swing.JTextField();
        subtotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();
        subtotalEmt = new javax.swing.JLabel();
        taxEmt = new javax.swing.JLabel();
        grandTotalEmt = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(183, 91, 91));
        backgroundPanel.setForeground(new java.awt.Color(240, 240, 240));

        storeLogoLabeleth.setIcon(new javax.swing.ImageIcon("JFRCVIFS.Student.UGDSB.ED\\Home\\Students\\JaSho9017\\Documents\\father.jpg")); // NOI18N

        storeLogoLabel.setIcon(new javax.swing.ImageIcon("JFRCVIFS.Student.UGDSB.ED\\Home\\Students\\JaSho9017\\Documents\\father.jpg")); // NOI18N

        titleLabel.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        titleLabel.setText("Father Tylers bakery and other stuff");

        subheading.setFont(new java.awt.Font("AlgerianBasDEE", 0, 11)); // NOI18N
        subheading.setText("Welcome to Father Tylers Store, where our products will give you an aneurism");

        subSubheading.setFont(new java.awt.Font("AlgerianBasDEE", 0, 11)); // NOI18N
        subSubheading.setForeground(new java.awt.Color(204, 255, 255));
        subSubheading.setText("type in the amount you require of each product");

        itemLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        itemLabel1.setText("AAAAAAAAAAA Cookies ($6)");

        amountSelectInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountSelectInputActionPerformed(evt);
            }
        });

        itemLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        itemLabel2.setText("Rage Quit Crumble ($5)");

        amountSelectInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountSelectInput2ActionPerformed(evt);
            }
        });

        subHeading2.setFont(new java.awt.Font("AlgerianBasDEE", 0, 11)); // NOI18N
        subHeading2.setForeground(new java.awt.Color(0, 255, 204));
        subHeading2.setText("items");

        subHeading3.setFont(new java.awt.Font("AlgerianBasDEE", 0, 11)); // NOI18N
        subHeading3.setForeground(new java.awt.Color(0, 255, 204));
        subHeading3.setText("Amount");

        itemLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        itemLabel3.setText("Aneurism Eclair ($3)");

        amountSelectInput3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountSelectInput3ActionPerformed(evt);
            }
        });

        subtotalLabel.setFont(new java.awt.Font("AlgerianBasDEE", 0, 11)); // NOI18N
        subtotalLabel.setText("subtotal :");

        taxLabel.setFont(new java.awt.Font("AlgerianBasDEE", 0, 11)); // NOI18N
        taxLabel.setText("Tax :");

        grandTotalLabel.setFont(new java.awt.Font("AlgerianBasDEE", 0, 11)); // NOI18N
        grandTotalLabel.setText("Grand total :");

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(storeLogoLabeleth)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subheading))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(titleLabel))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(subSubheading))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(subHeading2)
                        .addGap(172, 172, 172)
                        .addComponent(subHeading3))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(itemLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amountSelectInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(itemLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amountSelectInput, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(itemLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(subtotalLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(subtotalEmt))
                                    .addComponent(amountSelectInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(taxLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(taxEmt))
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(grandTotalLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(grandTotalEmt)))))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(storeLogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enterButton)
                .addGap(169, 169, 169))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subheading)
                        .addGap(18, 18, 18)
                        .addComponent(subSubheading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subHeading2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subHeading3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemLabel1)
                            .addComponent(amountSelectInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(storeLogoLabeleth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountSelectInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemLabel2))
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(amountSelectInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotalLabel)
                            .addComponent(subtotalEmt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxLabel)
                            .addComponent(taxEmt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandTotalLabel)
                            .addComponent(grandTotalEmt))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(storeLogoLabel))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountSelectInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountSelectInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountSelectInputActionPerformed

    private void amountSelectInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountSelectInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountSelectInput2ActionPerformed

    private void amountSelectInput3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountSelectInput3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountSelectInput3ActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        Scanner KeyedInput = new Scanner (System.in);
        double subtotal,tax,grandTotal,item1,item2,item3; 
        item1 = 6*Double.parseDouble(amountSelectInput.getText());
        item2 = 5*Double.parseDouble(amountSelectInput2.getText());
        item3 = 3*Double.parseDouble(amountSelectInput3.getText());
        subtotal = item1 + item2 + item3;
        tax = subtotal*0.13;
        grandTotal = subtotal - tax;
        taxEmt.setText ("$"+String.valueOf(tax));
        subtotalEmt.setText ("$"+String.valueOf(subtotal));     
        grandTotalEmt.setText ("$"+String.valueOf(grandTotal));
        
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makingPurchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountSelectInput;
    private javax.swing.JTextField amountSelectInput2;
    private javax.swing.JTextField amountSelectInput3;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel grandTotalEmt;
    private javax.swing.JLabel grandTotalLabel;
    private javax.swing.JLabel itemLabel1;
    private javax.swing.JLabel itemLabel2;
    private javax.swing.JLabel itemLabel3;
    private javax.swing.JLabel storeLogoLabel;
    private javax.swing.JLabel storeLogoLabeleth;
    private javax.swing.JLabel subHeading2;
    private javax.swing.JLabel subHeading3;
    private javax.swing.JLabel subSubheading;
    private javax.swing.JLabel subheading;
    private javax.swing.JLabel subtotalEmt;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel taxEmt;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
